70 buttonfix
plot-and-scatter/dchp3 pull request #104
Opened 2023-08-01 22:59 UTC by ericx057

Button fix - test, do not implement

2023-08-01 22:59 UTC, Shawk031 commented
test comment

2023-08-03 20:38 UTC, hangler requested changes
Thanks for this! My main feedback would be to incorporate some changes to make it easier for developers to use your component, rather than simply re-wrapping a `<button>` element.

2023-08-03 20:38 UTC, hangler commented on app/components/elements/Button.tsx
> +}
Let's have these `ButtonProps` extend the actual props for a `<button>` element. An example of how to do this with TypeScript is here: https://stackoverflow.com/a/62568833/715870

Then, you can delete the members of this `ButtonProps` interface that simply repeat existing props — in this case, that appears to be every member. However, what we can then do to make this really useful is add something like:

```tsx
interface ButtonProps {
  size?: 'small' | 'medium' | 'large' // We'll want to set 'medium' as the default later if this isn't passed
  appearance?: 'primary' | 'secondary' | 'danger' | 'success' // Set different colours based on this prop
}
```

Hopefully this makes sense. Let me know if not!

2023-08-14 20:45 UTC, hangler approved these changes
Looks good. Thank you!

2023-08-14 21:03 UTC, merged